name: 'Spotify - Play'
description: 'Play your favorite Spotify song from within GitHub'
author: 'Sebass van Boxel'
inputs:
  song:
    description: 'Song to search for'
    required: true
    default: ''
  device_id:
    device_id: 'Spotify device_id (https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/)'
    required: true
